name: Gradle Build + intTests

on:
  workflow_call:

jobs:
  intTest:
    name: gradle intTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.0
        with:
          cache-read-only: true

      - name: Run integration tests
        run: ./gradlew intTest -x test --no-daemon
